live_config_reload = true
working_directory = "None"

[env]
TERM = "xterm-256color"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[window]
decorations = "none"
startup_mode = "Fullscreen"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
- { key = "Right", mods = ["Alt"], chars = "\x1BF" },
- { key = "Left", mods = ["Alt"], chars = "\x1BB" },
]

[cursor]
style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true

[font]
size = 12

[font.bold]
family = "Fira Mono"
style = "Bold"

[font.normal]
family = "Fira Mono"
style = "Medium"

[colors.primary]
# background = '#0a0a05'
# background = '#0c0c05'
# background = '#4b3a10'
# background = '#6b4a25'
background = '#331a00'
foreground = '#f2f2f2'

[colors.normal]
black   = '#2e3436'
red     = '#cc0000'
green   = '#4e9a06'
yellow  = '#c4a000'
blue    = '#3465a4'
magenta = '#75507b'
cyan    = '#06989a'
white   = '#d3d7cf'

[colors.bright]
black   = '#555753'
red     = '#ef2929'
green   = '#8ae234'
yellow  = '#fce94f'
blue    = '#729fcf'
magenta = '#ad7fa8'
cyan    = '#34e2e2'
white   = '#eeeeec'
